In [1]:
import pandas as pd
import pyarrow as pa
from pathlib import Path

In [2]:
string_pa = pd.ArrowDtype(pa.string())

In [3]:
upc_columns = {
    "prestador": string_pa,
    "depto_prestador": string_pa,
    "mun_prestador": string_pa,
    "no_id": string_pa,
    "tipo_id": string_pa,
    "no_factura": string_pa,
}

In [4]:
upc_data_path = Path(
    r"C:\Users\CamiloAlexanderArias\Proyectos\python\retroactivos-clinica-colsanitas\outputs\upc_data.csv"
)
resultados_path = Path(
    r"C:\Users\CamiloAlexanderArias\Proyectos\python\retroactivos-clinica-colsanitas\outputs\resultados.csv"
)

In [5]:
df_upc = pd.read_csv(upc_data_path, sep="|", dtype=upc_columns, dtype_backend="pyarrow")
df_upc.head()

C:\Users\CamiloAlexanderArias\AppData\Local\Temp\ipykernel_29448\1478907086.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_upc = pd.read_csv(upc_data_path, sep="|", dtype=upc_columns, dtype_backend="pyarrow")

,id,id_agrupado,nmradica,hon,cia,cm,prestador,nom_prestador,depto_prestador,mun_prestador,...,desc_cod_dx,desc_cod_dx_rel,desc_munic_usu,desc_dep_usu,desc_reg_usu,desc_munic_pre,desc_dep_pre,desc_reg_pre,EDAD_EXACTA_AÑOS,llave_upc
0,46998292,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI1106231551INSUMO2025-07-24
1,47001990,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI1106231551INSUMO2025-07-24
2,47028049,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,FRACTURA DE LA EPIFISIS INFERIOR DEL HUMERO,FRACTURA DE LA EPIFISIS INFERIOR DEL HUMERO,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI11062315518732052025-07-24
3,47017912,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI1106231551INSUMO2025-07-24
4,47033892,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI11062315518907012025-07-24

In [6]:
columns_resultado = {
    "num factura": string_pa,
    "tip doc": string_pa,
    "num doc": string_pa,
    "Codigo Cups": string_pa,
}

In [7]:
df_resultado = pd.read_csv(
    resultados_path, sep="|", dtype=columns_resultado, dtype_backend="pyarrow"
)
df_resultado

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,val total cargo,fecha factura,Fecha Ingreso,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,17311,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,902210,18211,18211.0,900.0,118839897CC11104539369022102025-08-29,SI
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,19527,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,890701,20542,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,4683,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,901107,4927,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,5949,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,907106,6258,6258.0,309.0,118839896RC11106118229071062025-08-30,SI
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,17311,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,902210,18211,18211.0,900.0,118839896RC10839430589022102025-08-30,SI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74737,118842701,CLINICA KERALTY IBAGUE,CC,93358730,GERARDO,<NA>,VELASQUEZ,CALDERON,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC933587308905022025-08-19,SI
74738,118842701,CLINICA KERALTY IBAGUE,CC,41707869,MARIA,ANABOLENA,TORRES,SABOGAL,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC417078698905022025-08-19,SI
74739,118842701,CLINICA KERALTY IBAGUE,CC,8297568,MARIO,IVAN,AGUIRRE,PEREZ,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC82975688905022025-08-19,SI
74740,118842701,CLINICA KERALTY IBAGUE,CC,41662425,MARIA,USDIOLA,AGUIRRE,GALVEZ,P,2025,...,85556,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,861402,90005,90005.0,4449.0,118842701CC416624258614022025-08-19,SI
74741,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,313424669.05,<NA>,NO

In [8]:
df_upc.shape

(108354, 90)

In [9]:
df_upc.loc[
    df_upc.duplicated(
        subset=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], keep=False
    )
].sort_values(
    by=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], ascending=[True] * 5
)[["no_factura", "tipo_id", "no_id", "cups", "desc_cups", "f_prestacion", "vr_neto"]]

,no_factura,tipo_id,no_id,cups,desc_cups,f_prestacion,vr_neto
2,118839880,TI,1106231551,873205,RADIOGRAFIA DE CODO,2025-07-24,23150
24,118839880,TI,1106231551,873205,RADIOGRAFIA DE CODO,2025-07-24,23150
0,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,28655
1,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,5743
3,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,3429
...,...,...,...,...,...,...,...
108208,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,3387
108296,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,11493
108302,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,1694
108173,118842701,CC,93404091,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-15,10696
108238,118842701,CC,93404091,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-15,7840

In [10]:
df_tarifas_2025 = pd.read_excel(
    r"C:\Users\CamiloAlexanderArias\Proyectos\python\retroactivos-clinica-colsanitas\inputs\30348_ANEXO_800149384_CLINICA KERALTY IBAGUE (2025).xlsx",
    sheet_name="ANEXO",
    skiprows=18,
    dtype_backend="pyarrow",
)

df_tarifas_2025.head()

,Unnamed: 0,TIPO,COD REPS,INTERDEPENDECIA,CODIGO DE HABILITACION - INTERDEPENDENCIA,COD\n(Res Vigente),DESCRIPCION COD (Res Vigente),COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,...,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $2,100","ANESTESIA UVR $1,587",AYUDANTIA UVR $595,"D SALA Mayor 450 UVR $2,331",MATERIALES,TOTAL,OBSERVACIONES,xxx
0,None,EV,1102,NO,NO_APLICA,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,No,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,20542,<NA>,None
1,None,EV,706,NO,NO_APLICA,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,No,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,18211,<NA>,None
2,None,EV,129,NO,NO_APLICA,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,No,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,24957,<NA>,None
3,None,EV,706,NO,NO_APLICA,903895,CREATININA EN SUERO U OTROS FLUIDOS,903895,CREATININA EN SUERO U OTROS FLUIDOS,No,...,PROPIA,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,4773,<NA>,None
4,None,EV,706,NO,NO_APLICA,903883,GLUCOSA SEMIAUTOMATIZADA [GLUCOMETRÍA],903883,GLUCOSA SEMIAUTOMATIZADA [GLUCOMETRIA],No,...,PROPIA,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,4322,<NA>,None

In [11]:
df_merge_upc = df_upc.merge(
    df_tarifas_2025.dropna(subset=["COD EPS"]),
    how="left",
    left_on="cups",
    right_on="COD EPS",
    suffixes=("_upc", "_tarifa2025"),
)

df_merge_upc.head()

,id,id_agrupado,nmradica,hon,cia,cm,prestador,nom_prestador,depto_prestador,mun_prestador,...,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $2,100","ANESTESIA UVR $1,587",AYUDANTIA UVR $595,"D SALA Mayor 450 UVR $2,331",MATERIALES,TOTAL,OBSERVACIONES,xxx
0,46998292,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
1,47001990,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
2,47028049,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,24353,<NA>,None
3,47017912,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
4,47033892,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,20542,<NA>,None

In [12]:
df_upc.shape

(108354, 90)

In [13]:
df_merge_upc.shape

(108354, 113)

In [14]:
df_merge_upc.loc[
    df_merge_upc.duplicated(
        subset=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], keep=False
    )
].sort_values(
    by=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], ascending=[True] * 5
)[
    [
        "no_factura",
        "tipo_id",
        "no_id",
        "cups",
        "desc_cups",
        "f_prestacion",
        "vr_neto",
        "TOTAL",
    ]
]

,no_factura,tipo_id,no_id,cups,desc_cups,f_prestacion,vr_neto,TOTAL
2,118839880,TI,1106231551,873205,RADIOGRAFIA DE CODO,2025-07-24,23150,24353
24,118839880,TI,1106231551,873205,RADIOGRAFIA DE CODO,2025-07-24,23150,24353
0,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,28655,<NA>
1,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,5743,<NA>
3,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,3429,<NA>
...,...,...,...,...,...,...,...,...
108208,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,3387,<NA>
108296,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,11493,<NA>
108302,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,1694,<NA>
108173,118842701,CC,93404091,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-15,10696,<NA>
108238,118842701,CC,93404091,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-15,7840,<NA>

In [15]:
df_merge_upc.loc[
    df_merge_upc.duplicated(
        subset=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], keep=False
    )
].sort_values(
    by=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], ascending=[True] * 5
)

,id,id_agrupado,nmradica,hon,cia,cm,prestador,nom_prestador,depto_prestador,mun_prestador,...,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $2,100","ANESTESIA UVR $1,587",AYUDANTIA UVR $595,"D SALA Mayor 450 UVR $2,331",MATERIALES,TOTAL,OBSERVACIONES,xxx
2,47028049,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,24353,<NA>,None
24,46982737,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,24353,<NA>,None
0,46998292,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
1,47001990,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
3,47017912,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108208,50693678,None,1792991590,SERVICIOS DE CIRUGIAS AMBULATORIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
108296,50756477,None,1792991590,SERVICIOS DE CIRUGIAS AMBULATORIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
108302,50755269,None,1792991590,SERVICIOS DE CIRUGIAS AMBULATORIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
108173,52464411,None,1792991590,SERVICIOS DE CIRUGIAS AMBULATORIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
108238,52464410,None,1792991590,SERVICIOS DE CIRUGIAS AMBULATORIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None

In [16]:
df_resultado.loc[
    df_resultado.duplicated(
        subset=["num factura", "tip doc", "num doc", "Codigo Cups"], keep=False
    )
]

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,val total cargo,fecha factura,Fecha Ingreso,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc
6,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,4108,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,903883,4322,4322.0,214.0,118839896RC10839430589038832025-08-30,SI
41,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,4108,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,903883,4322,4322.0,214.0,118839896RC10839430589038832025-08-30,SI
66,118839896,CLINICA KERALTY IBAGUE,CC,1102859192,DANIA,CAROLINA,VILLAMIL,MARTINEZ,U,2025,...,5949,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,907106,6258,6258.0,309.0,118839896CC11028591929071062025-08-30,SI
70,118839896,CLINICA KERALTY IBAGUE,CC,1102859192,DANIA,CAROLINA,VILLAMIL,MARTINEZ,U,2025,...,291875,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,879430,307053,307053.0,15178.0,118839896CC11028591928794302025-08-30,SI
78,118839896,CLINICA KERALTY IBAGUE,CC,1102859192,DANIA,CAROLINA,VILLAMIL,MARTINEZ,U,2025,...,5949,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,907106,6258,6258.0,309.0,118839896CC11028591929071062025-08-30,SI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74651,118842624,CLINICA KERALTY IBAGUE,CN,25103510334334,HIJA DE MARIA,FERNANDA,PUERTO,SANCHEZ,H,2025,...,23723,2025-10-30 15:55:37.580000,2025-10-03 00:00:00,2025-10-05 00:00:00,890602,24957,24957.0,1234.0,118842624CN251035103343348906022025-10-05,NO
74662,118842701,CLINICA KERALTY IBAGUE,CC,41605919,AMPARO,<NA>,RAMIREZ,VALENCIA,P,2025,...,79167,2025-10-31 00:00:00,2025-07-31 00:00:00,2025-07-31 00:00:00,992990,83284,83284.0,4117.0,118842701CC416059199929902025-07-31,SI
74685,118842701,CLINICA KERALTY IBAGUE,CC,38246209,MARIA,LILIA,LEYTON,RODRIGUEZ,P,2025,...,79167,2025-10-31 00:00:00,2025-08-01 00:00:00,2025-08-01 00:00:00,992990,83284,83284.0,4117.0,118842701CC382462099929902025-08-01,SI
74695,118842701,CLINICA KERALTY IBAGUE,CC,38246209,MARIA,LILIA,LEYTON,RODRIGUEZ,P,2025,...,79167,2025-10-31 00:00:00,2025-08-07 00:00:00,2025-08-07 00:00:00,992990,83284,83284.0,4117.0,118842701CC382462099929902025-08-07,NO
74710,118842701,CLINICA KERALTY IBAGUE,CC,41605919,AMPARO,<NA>,RAMIREZ,VALENCIA,P,2025,...,79167,2025-10-31 00:00:00,2025-08-11 00:00:00,2025-08-11 00:00:00,992990,83284,83284.0,4117.0,118842701CC416059199929902025-08-11,NO

In [17]:
# df_resultado.drop_duplicates(inplace=True)

In [18]:
df_resultado

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,val total cargo,fecha factura,Fecha Ingreso,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,17311,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,902210,18211,18211.0,900.0,118839897CC11104539369022102025-08-29,SI
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,19527,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,890701,20542,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,4683,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,901107,4927,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,5949,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,907106,6258,6258.0,309.0,118839896RC11106118229071062025-08-30,SI
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,17311,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,902210,18211,18211.0,900.0,118839896RC10839430589022102025-08-30,SI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74737,118842701,CLINICA KERALTY IBAGUE,CC,93358730,GERARDO,<NA>,VELASQUEZ,CALDERON,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC933587308905022025-08-19,SI
74738,118842701,CLINICA KERALTY IBAGUE,CC,41707869,MARIA,ANABOLENA,TORRES,SABOGAL,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC417078698905022025-08-19,SI
74739,118842701,CLINICA KERALTY IBAGUE,CC,8297568,MARIO,IVAN,AGUIRRE,PEREZ,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC82975688905022025-08-19,SI
74740,118842701,CLINICA KERALTY IBAGUE,CC,41662425,MARIA,USDIOLA,AGUIRRE,GALVEZ,P,2025,...,85556,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,861402,90005,90005.0,4449.0,118842701CC416624258614022025-08-19,SI
74741,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,313424669.05,<NA>,NO

In [19]:
agrupacion_costo_upc = df_upc.groupby(
    ["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], as_index=False
).agg({"vr_neto": "sum"})

agrupacion_costo_upc

      no_factura tipo_id       no_id    cups f_prestacion  vr_neto
0      118839880      TI  1106231551  361916   2025-07-24    37464
1      118839880      TI  1106231551  5DS004   2025-07-24    52540
2      118839880      TI  1106231551  793204   2025-07-24   806051
3      118839880      TI  1106231551  873121   2025-07-24    30002
4      118839880      TI  1106231551  873205   2025-07-24    46300
...          ...     ...         ...     ...          ...      ...
60447    1419129      TI  1110499859  890236   2025-09-12    43808
60448    1419129      TI  1139224382  890336   2025-09-29    43242
60449    1419129      TI  1141721700  890236   2025-09-22    43808
60450    1419129      TI  1197468881  890294   2025-09-23    51798
60451    1419129      TI  1233505893  890336   2025-09-01    43242

[60452 rows x 6 columns]

In [20]:
df_resultado_merge_upc = df_resultado.merge(
    agrupacion_costo_upc,
    how="left",
    left_on=["num factura", "tip doc", "num doc", "Codigo Cups", "fec cargo"],
    right_on=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"],
    suffixes=("_resultado", "_upc"),
)

df_resultado_merge_upc.drop(
    columns=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], inplace=True
)

df_resultado_merge_upc.head()

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,fecha factura,Fecha Ingreso,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc,vr_neto
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,902210,18211,18211.0,900.0,118839897CC11104539369022102025-08-29,SI,17311
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,890701,20542,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI,19527
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,901107,4927,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO,<NA>
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,907106,6258,6258.0,309.0,118839896RC11106118229071062025-08-30,SI,5949
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,902210,18211,18211.0,900.0,118839896RC10839430589022102025-08-30,SI,17311

In [21]:
df_resultado_merge_upc

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,fecha factura,Fecha Ingreso,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc,vr_neto
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,902210,18211,18211.0,900.0,118839897CC11104539369022102025-08-29,SI,17311
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,890701,20542,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI,19527
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,901107,4927,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO,<NA>
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,907106,6258,6258.0,309.0,118839896RC11106118229071062025-08-30,SI,5949
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,902210,18211,18211.0,900.0,118839896RC10839430589022102025-08-30,SI,17311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74737,118842701,CLINICA KERALTY IBAGUE,CC,93358730,GERARDO,<NA>,VELASQUEZ,CALDERON,P,2025,...,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC933587308905022025-08-19,SI,128400
74738,118842701,CLINICA KERALTY IBAGUE,CC,41707869,MARIA,ANABOLENA,TORRES,SABOGAL,P,2025,...,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC417078698905022025-08-19,SI,128400
74739,118842701,CLINICA KERALTY IBAGUE,CC,8297568,MARIO,IVAN,AGUIRRE,PEREZ,P,2025,...,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC82975688905022025-08-19,SI,128400
74740,118842701,CLINICA KERALTY IBAGUE,CC,41662425,MARIA,USDIOLA,AGUIRRE,GALVEZ,P,2025,...,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,861402,90005,90005.0,4449.0,118842701CC416624258614022025-08-19,SI,85556
74741,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,313424669.05,<NA>,NO,<NA>

In [22]:
df_tarifas_2024_27000 = pd.read_excel(
    r"C:\Users\CamiloAlexanderArias\Proyectos\python\retroactivos-clinica-colsanitas\inputs\27000_ANEXO_800149384_CLINICA KERALTY IBAGUE_(2024).xlsx",
    sheet_name="ANEXO",
    skiprows=17,
    dtype_backend="pyarrow",
)

df_tarifas_2024_27000.head()

,Unnamed: 0,TIPO,COD REPS,COD\n(Res Vigente 2336 de 2023),COD IPS,DESCRIPCION IPS,COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),...,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $1,996","ANESTESIA UVR $1,509",AYUDANTIA UVR $566,"D SALA Mayor 450 UVR $2,216",MATERIALES,TOTAL,OBSERVACIONES,Unnamed: 20
0,None,EV,1102,890701,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,No,890701,...,VALOR,"ISS 2001+57,16%",<NA>,<NA>,<NA>,<NA>,<NA>,19527,<NA>,None
1,None,EV,706,902210,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,No,902210,...,VALOR,"ISS 2001+57,16%",<NA>,<NA>,<NA>,<NA>,<NA>,17311,<NA>,None
2,None,EV,129,890602,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,No,890602,...,VALOR,"ISS 2001+57,16%",<NA>,<NA>,<NA>,<NA>,<NA>,23723,<NA>,None
3,None,EV,706,903895,903895,CREATININA EN SUERO U OTROS FLUIDOS,903895,CREATININA EN SUERO U OTROS FLUIDOS,No,<NA>,...,PROPIA,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,4537,<NA>,None
4,None,EV,706,903856,903856,NITROGENO UREICO,903856,NITROGENO UREICO,No,903856,...,VALOR,"ISS 2001+57,16%",<NA>,<NA>,<NA>,<NA>,<NA>,5760,<NA>,None

In [23]:
df_tarifas_2024_27467 = pd.read_excel(
    r"C:\Users\CamiloAlexanderArias\Proyectos\python\retroactivos-clinica-colsanitas\inputs\27467_ANEXO_800149384_CLINICA KERALTY IBAGUE_(2024).xlsx",
    sheet_name="ANEXO",
    skiprows=17,
    dtype_backend="pyarrow",
)

df_tarifas_2024_27467.head()

,Unnamed: 0,TIPO,COD REPS,COD\n(Res Vigente 2336 de 2023),COD IPS,DESCRIPCION IPS,COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),UVR/VALOR,TARIFA DEFINIDA,HONORARIO,ANESTESIA,AYUDANTIA,D SALA,MATERIALES,TOTAL,OBSERVACIONES,AMBITO
0,None,EV,129,890474,890474,INTERCONSULTA POR ESPECIALISTA EN NEUROLOGÍA,890474,INTERCONSULTA POR NEUROLOGIA,No,<NA>,<NA>,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,84637,<NA>,H-U
1,None,EV,129,890433,890433,INTERCONSULTA POR ESPECIALISTA EN CIRUGÍA DE T...,890433,INTERCONSULTA POR CIRUGIA DE TORAX,No,<NA>,<NA>,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,64200,<NA>,H-U
2,None,PQ,215,601101,601101PQ,BIOPSIA CERRADA DE PROSTATA POR ABORDAJE TRANS...,601101PQ,BIOPSIA CERRADA DE PROSTATA POR ABORDAJE TRANS...,No,<NA>,<NA>,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,1526960,Se solicita Replica de Paquete,A-H
3,None,EV,234,324102,324102,LOBECTOMÍA SEGMENTARIA POR TORACOSCOPIA,324102,LOBECTOMIA SEGMENTARIA POR TORACOSCOPIA,Si,323100,150,"PROPIA HON Demas Componentes ISS 2001+57,16%",2700000,226350,84900,292962,220213,3524425,<NA>,H
4,None,PQ,215,601103,601103PQ,BIOPSIA CERRADA DE PROSTATA POR SATURACION ABO...,601103PQ,BIOPSIA CERRADA DE PROSTATA POR SATURACION ABO...,No,<NA>,<NA>,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,1046460,Se solicita Replica de Paquete,A-H

In [24]:
df_tarifas_2024_27467.dropna(subset=["COD EPS"], inplace=True)
df_tarifas_2024_27000.dropna(subset=["COD EPS"], inplace=True)

In [25]:
df_tarifas_2024_27467.shape

(12, 20)

In [26]:
df_tarifas_2024_27000.shape

(5404, 21)

In [27]:
df_tarifas_2024_27467.loc[
    df_tarifas_2024_27467["COD EPS"].isin(df_tarifas_2024_27000["COD EPS"].unique())
]

Empty DataFrame
Columns: [Unnamed: 0, TIPO, COD REPS, COD
(Res Vigente 2336 de 2023), COD IPS, DESCRIPCION IPS, COD EPS, DESCRIPCION CUPS, HABILITA CONCEPTOS, COD HOMOLOGO Manual tarifario
(ISS o SOAT), UVR/VALOR, TARIFA DEFINIDA, HONORARIO, ANESTESIA, AYUDANTIA, D SALA, MATERIALES, TOTAL, OBSERVACIONES, AMBITO]
Index: []

In [28]:
df_tarifas_2024 = pd.concat(
    [df_tarifas_2024_27000, df_tarifas_2024_27467], ignore_index=True
)

df_tarifas_2024.head()

,Unnamed: 0,TIPO,COD REPS,COD\n(Res Vigente 2336 de 2023),COD IPS,DESCRIPCION IPS,COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),...,"D SALA Mayor 450 UVR $2,216",MATERIALES,TOTAL,OBSERVACIONES,Unnamed: 20,HONORARIO,ANESTESIA,AYUDANTIA,D SALA,AMBITO
0,None,EV,1102,890701,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,No,890701,...,<NA>,<NA>,19527,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>
1,None,EV,706,902210,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,No,902210,...,<NA>,<NA>,17311,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>
2,None,EV,129,890602,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,No,890602,...,<NA>,<NA>,23723,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>
3,None,EV,706,903895,903895,CREATININA EN SUERO U OTROS FLUIDOS,903895,CREATININA EN SUERO U OTROS FLUIDOS,No,<NA>,...,<NA>,<NA>,4537,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>
4,None,EV,706,903856,903856,NITROGENO UREICO,903856,NITROGENO UREICO,No,903856,...,<NA>,<NA>,5760,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>

In [29]:
df_resultado_merge_tarifas_2024 = df_resultado_merge_upc.merge(
    df_tarifas_2024,
    how="left",
    left_on="Codigo Cups",
    right_on="COD EPS",
    suffixes=("_upc", "_tarifa2024"),
)

In [30]:
df_resultado_merge_tarifas_2025 = df_resultado_merge_tarifas_2024.merge(
    df_tarifas_2025.dropna(subset=["COD EPS"]),
    how="left",
    left_on="Codigo Cups",
    right_on="COD EPS",
    suffixes=("_tarifa2024", "_tarifa2025"),
)

In [31]:
df_resultado_merge_tarifas_2025

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,FORMA DE LIQUIDAR_tarifa2025,TARIFA DEFINIDA_tarifa2025,"HONORARIO UVR $2,100","ANESTESIA UVR $1,587",AYUDANTIA UVR $595,"D SALA Mayor 450 UVR $2,331",MATERIALES_tarifa2025,TOTAL_tarifa2025,OBSERVACIONES_tarifa2025,xxx
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,18211,<NA>,None
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,20542,<NA>,None
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,6258,<NA>,None
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,VALOR,"ISS 2001+65,33%",<NA>,<NA>,<NA>,<NA>,<NA>,18211,<NA>,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74737,118842701,CLINICA KERALTY IBAGUE,CC,93358730,GERARDO,<NA>,VELASQUEZ,CALDERON,P,2025,...,PROPIA,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,135077,<NA>,None
74738,118842701,CLINICA KERALTY IBAGUE,CC,41707869,MARIA,ANABOLENA,TORRES,SABOGAL,P,2025,...,PROPIA,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,135077,<NA>,None
74739,118842701,CLINICA KERALTY IBAGUE,CC,8297568,MARIO,IVAN,AGUIRRE,PEREZ,P,2025,...,PROPIA,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,135077,<NA>,None
74740,118842701,CLINICA KERALTY IBAGUE,CC,41662425,MARIA,USDIOLA,AGUIRRE,GALVEZ,P,2025,...,PROPIA,PROPIA,90005,<NA>,<NA>,<NA>,<NA>,90005,<NA>,None
74741,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None

In [32]:
df_resultado_merge_tarifas_2025.columns.to_list()

['num factura',
 'desc sucur',
 'tip doc',
 'num doc',
 'pri nom',
 'seg nom',
 'pri ape',
 'seg ape',
 'tip admision',
 'ano adm',
 'num adm',
 'desc entidad',
 'fec cargo',
 'ano cargo',
 'mes cargo',
 'Codigo Cups',
 'desc insumo servicio',
 'desc concepto',
 'valor unit',
 'cantidad',
 'val total cargo',
 'fecha factura',
 'Fecha Ingreso',
 'Fecha Egreso',
 'CODIGO BH',
 'TARIFA 2025',
 'TARIFA VRS CANTIDAD',
 'VALOR RETROACTIVO',
 'llave_retroactivo',
 'encontrado_upc',
 'vr_neto',
 'Unnamed: 0_tarifa2024',
 'TIPO_tarifa2024',
 'COD REPS_tarifa2024',
 'COD\n(Res Vigente 2336 de 2023)',
 'COD IPS',
 'DESCRIPCION IPS',
 'COD EPS_tarifa2024',
 'DESCRIPCION CUPS_tarifa2024',
 'HABILITA CONCEPTOS_tarifa2024',
 'COD HOMOLOGO Manual tarifario\n(ISS o SOAT)_tarifa2024',
 'UVR/VALOR_tarifa2024',
 'FORMA DE LIQUIDAR_tarifa2024',
 'TARIFA DEFINIDA_tarifa2024',
 'HONORARIO UVR $1,996',
 'ANESTESIA UVR $1,509',
 'AYUDANTIA UVR $566',
 'D SALA Mayor 450 UVR $2,216',
 'MATERIALES_tarifa2024',
 'TOTAL_tarifa2024',
 'OBSERVACIONES_tarifa2024',
 'Unnamed: 20',
 'HONORARIO',
 'ANESTESIA',
 'AYUDANTIA',
 'D SALA',
 'AMBITO',
 'Unnamed: 0_tarifa2025',
 'TIPO_tarifa2025',
 'COD REPS_tarifa2025',
 'INTERDEPENDECIA ',
 'CODIGO DE HABILITACION - INTERDEPENDENCIA',
 'COD\n(Res Vigente)',
 'DESCRIPCION COD (Res Vigente)',
 'COD EPS_tarifa2025',
 'DESCRIPCION CUPS_tarifa2025',
 'HABILITA CONCEPTOS_tarifa2025',
 'COD HOMOLOGO Manual tarifario\n(ISS o SOAT)_tarifa2025',
 'GRUPO_SALARIOS',
 'UVR/VALOR_tarifa2025',
 'FORMA DE LIQUIDAR_tarifa2025',
 'TARIFA DEFINIDA_tarifa2025',
 'HONORARIO UVR $2,100',
 'ANESTESIA UVR $1,587',
 'AYUDANTIA UVR $595',
 'D SALA Mayor 450 UVR $2,331',
 'MATERIALES_tarifa2025',
 'TOTAL_tarifa2025',
 'OBSERVACIONES_tarifa2025',
 'xxx']

In [33]:
cols_salida = [
    "num factura",
    "desc sucur",
    "tip doc",
    "num doc",
    "pri nom",
    "seg nom",
    "pri ape",
    "seg ape",
    "tip admision",
    "ano adm",
    "num adm",
    "desc entidad",
    "fec cargo",
    "ano cargo",
    "mes cargo",
    "Codigo Cups",
    "desc insumo servicio",
    "desc concepto",
    "valor unit",
    "cantidad",
    "val total cargo",
    "fecha factura",
    "Fecha Ingreso",
    "Fecha Egreso",
    "CODIGO BH",
    "TARIFA 2025",
    "TARIFA VRS CANTIDAD",
    "VALOR RETROACTIVO",
    "llave_retroactivo",
    "encontrado_upc",
    "vr_neto",
    "TOTAL_tarifa2024",
    "TOTAL_tarifa2025",
]

In [34]:
df_salida_resultado_ibague = df_resultado_merge_tarifas_2025[cols_salida].copy()

In [35]:
df_salida_resultado_ibague

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc,vr_neto,TOTAL_tarifa2024,TOTAL_tarifa2025
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-08-31 00:00:00,902210,18211,18211.0,900.0,118839897CC11104539369022102025-08-29,SI,17311,17311,18211
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-08-31 00:00:00,890701,20542,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI,19527,19527,20542
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-08-31 00:00:00,901107,4927,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO,<NA>,<NA>,<NA>
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-08-31 00:00:00,907106,6258,6258.0,309.0,118839896RC11106118229071062025-08-30,SI,5949,5949,6258
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,2025-08-30 00:00:00,902210,18211,18211.0,900.0,118839896RC10839430589022102025-08-30,SI,17311,17311,18211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74737,118842701,CLINICA KERALTY IBAGUE,CC,93358730,GERARDO,<NA>,VELASQUEZ,CALDERON,P,2025,...,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC933587308905022025-08-19,SI,128400,128400,135077
74738,118842701,CLINICA KERALTY IBAGUE,CC,41707869,MARIA,ANABOLENA,TORRES,SABOGAL,P,2025,...,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC417078698905022025-08-19,SI,128400,128400,135077
74739,118842701,CLINICA KERALTY IBAGUE,CC,8297568,MARIO,IVAN,AGUIRRE,PEREZ,P,2025,...,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC82975688905022025-08-19,SI,128400,128400,135077
74740,118842701,CLINICA KERALTY IBAGUE,CC,41662425,MARIA,USDIOLA,AGUIRRE,GALVEZ,P,2025,...,2025-08-19 00:00:00,861402,90005,90005.0,4449.0,118842701CC416624258614022025-08-19,SI,85556,85556,90005
74741,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,313424669.05,<NA>,NO,<NA>,<NA>,<NA>

## Operaciones

In [36]:
# vr_neto upc / total_2024 = porcentaje_upc_costo_2024
# porcentaje_upc_costo_2024 * total_2025 = vr_neto 2025
# vr_neto 2025 - vr_neto upc = retroactivo

In [37]:
df_salida_resultado_ibague = df_salida_resultado_ibague.assign(
    porcentaje_upc_costo_2024=lambda df_: df_["vr_neto"] / df_["TOTAL_tarifa2024"],
    vr_neto_2025=lambda df_: df_["porcentaje_upc_costo_2024"] * df_["TOTAL_tarifa2025"],
    valor_retroactivo=lambda df_: df_["vr_neto_2025"] - df_["vr_neto"],
)

In [38]:
df_salida_resultado_ibague

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc,vr_neto,TOTAL_tarifa2024,TOTAL_tarifa2025,porcentaje_upc_costo_2024,vr_neto_2025,valor_retroactivo
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,18211.0,900.0,118839897CC11104539369022102025-08-29,SI,17311,17311,18211,1.0,18211.0,900.0
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI,19527,19527,20542,1.0,20542.0,1015.0
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,6258.0,309.0,118839896RC11106118229071062025-08-30,SI,5949,5949,6258,1.0,6258.0,309.0
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,18211.0,900.0,118839896RC10839430589022102025-08-30,SI,17311,17311,18211,1.0,18211.0,900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74737,118842701,CLINICA KERALTY IBAGUE,CC,93358730,GERARDO,<NA>,VELASQUEZ,CALDERON,P,2025,...,135077.0,6677.0,118842701CC933587308905022025-08-19,SI,128400,128400,135077,1.0,135077.0,6677.0
74738,118842701,CLINICA KERALTY IBAGUE,CC,41707869,MARIA,ANABOLENA,TORRES,SABOGAL,P,2025,...,135077.0,6677.0,118842701CC417078698905022025-08-19,SI,128400,128400,135077,1.0,135077.0,6677.0
74739,118842701,CLINICA KERALTY IBAGUE,CC,8297568,MARIO,IVAN,AGUIRRE,PEREZ,P,2025,...,135077.0,6677.0,118842701CC82975688905022025-08-19,SI,128400,128400,135077,1.0,135077.0,6677.0
74740,118842701,CLINICA KERALTY IBAGUE,CC,41662425,MARIA,USDIOLA,AGUIRRE,GALVEZ,P,2025,...,90005.0,4449.0,118842701CC416624258614022025-08-19,SI,85556,85556,90005,1.0,90005.0,4449.0
74741,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,313424669.05,<NA>,NO,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [39]:
df_salida_resultado_ibague.loc[df_salida_resultado_ibague.porcentaje_upc_costo_2024 < 1]

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc,vr_neto,TOTAL_tarifa2024,TOTAL_tarifa2025,porcentaje_upc_costo_2024,vr_neto_2025,valor_retroactivo
527,118839886,CLINICA KERALTY IBAGUE,TI,1197464798,JUAN,DIEGO,VANEGAS,HERNANDEZ,A,2025,...,63000.0,3120.0,118839886TI11974647986251042025-07-28,SI,184424,362140,380935,0.509262,193995.571989,9571.571989
590,118839890,CLINICA KERALTY IBAGUE,CC,19369358,HECTOR,<NA>,RODRIGUEZ,<NA>,A,2025,...,262500.0,13000.0,118839890CC193693585310022025-08-15,SI,927133,955508,1005101,0.970304,975253.274104,48120.274104
604,118839892,CLINICA KERALTY IBAGUE,CC,93135705,DIBER,ALEJANDRO,PRADA,SANCHEZ,A,2025,...,126000.0,6240.0,118839892CC931357055340012025-08-26,SI,371835,462061,486043,0.804731,391134.068673,19299.068673
1129,118839903,CLINICA KERALTY IBAGUE,CC,14210288,JOSE,REINERIO,GUZMAN,DIAZ,A,2025,...,357053.0,17649.0,118839903CC142102888641012025-08-26,SI,497994,521375,548466,0.955155,523870.10732,25876.10732
1131,118839903,CLINICA KERALTY IBAGUE,CC,14210288,JOSE,REINERIO,GUZMAN,DIAZ,A,2025,...,120150.6,5939.6,118839903CC142102888642022025-08-26,SI,175017,452693,476186,0.386613,184099.699271,9082.699271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74104,118842497,CLINICA KERALTY IBAGUE,CC,65738049,MARIA,ELINA,CASTAÃ‘EDA,ROMERO,P,2025,...,157500.0,7800.0,118842497CC657380495732012025-10-17,SI,171011,625051,657497,0.273595,179888.072281,8877.072281
74105,118842497,CLINICA KERALTY IBAGUE,CC,38257516,MARTHA,LILIA,DURAN,MORALES,P,2025,...,157500.0,7800.0,118842497CC382575165732012025-10-17,SI,171011,625051,657497,0.273595,179888.072281,8877.072281
74106,118842497,CLINICA KERALTY IBAGUE,CC,38258660,NIDIA,ESPERANZA,PRADA,ROBAYO,P,2025,...,157500.0,7800.0,118842497CC382586605732012025-10-17,SI,171011,625051,657497,0.273595,179888.072281,8877.072281
74107,118842497,CLINICA KERALTY IBAGUE,CC,65752539,ROSA,<NA>,RODRIGUEZ,CASTELLANOS,P,2025,...,157500.0,7800.0,118842497CC657525395732012025-10-17,SI,171011,625051,657497,0.273595,179888.072281,8877.072281
74108,118842497,CLINICA KERALTY IBAGUE,CC,93392699,RUBEN,DARIO,VARGAS,BETANCUR,P,2025,...,157500.0,7800.0,118842497CC933926995732012025-10-17,SI,171011,625051,657497,0.273595,179888.072281,8877.072281

In [40]:
df_salida_resultado_ibague["encontrado_upc"].value_counts()

encontrado_upc
SI    42038
NO    32704
Name: count, dtype: int64[pyarrow]

In [41]:
df_salida_resultado_ibague["valor_retroactivo"].sum()
196_036_080.6771898

196036080.6771898

In [42]:
df_salida_resultado_ibague["VALOR RETROACTIVO"].sum()

626849338.0999999

In [43]:
623_276_300.0999999 - 196_036_080.6771898

427240219.4228101

In [44]:
427_240_219.4228101

427240219.4228101

In [45]:
df_salida_resultado_ibague.loc[df_salida_resultado_ibague["encontrado_upc"] == "NO"][
    "VALOR RETROACTIVO"
].sum()

495102723.25

In [46]:
492_501_232.25 + 196036080.6771898

688537312.9271898

In [47]:
df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["TOTAL_tarifa2024"]
    < df_salida_resultado_ibague["vr_neto"]
]

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc,vr_neto,TOTAL_tarifa2024,TOTAL_tarifa2025,porcentaje_upc_costo_2024,vr_neto_2025,valor_retroactivo
6,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,4322.0,214.0,118839896RC10839430589038832025-08-30,SI,8216,4108,4322,2.0,8644.0,428.0
41,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,4322.0,214.0,118839896RC10839430589038832025-08-30,SI,8216,4108,4322,2.0,8644.0,428.0
66,118839896,CLINICA KERALTY IBAGUE,CC,1102859192,DANIA,CAROLINA,VILLAMIL,MARTINEZ,U,2025,...,6258.0,309.0,118839896CC11028591929071062025-08-30,SI,11898,5949,6258,2.0,12516.0,618.0
78,118839896,CLINICA KERALTY IBAGUE,CC,1102859192,DANIA,CAROLINA,VILLAMIL,MARTINEZ,U,2025,...,6258.0,309.0,118839896CC11028591929071062025-08-30,SI,11898,5949,6258,2.0,12516.0,618.0
153,118839896,CLINICA KERALTY IBAGUE,CC,19489907,JORGE,ELIECER,BUSTOS,ORDOÑEZ,U,2025,...,64875.0,3205.0,118839896CC194899079034392025-08-30,SI,123340,61670,64875,2.0,129750.0,6410.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74707,118842701,CLINICA KERALTY IBAGUE,CC,38221131,LUZMILA,<NA>,RINCON,CORTES,P,2025,...,249852.0,12351.0,118842701CC382211319929902025-08-08,SI,237501,79167,83284,3.0,249852.0,12351.0
74711,118842701,CLINICA KERALTY IBAGUE,CC,65755489,ANA,MARIA,BONILLA,BENITEZ,P,2025,...,482036.0,23820.0,118842701CC657554898614112025-08-11,SI,458216,229108,241018,2.0,482036.0,23820.0
74712,118842701,CLINICA KERALTY IBAGUE,CC,1110504716,DIANA,CAROLINA,CELEMIN,VERA,P,2025,...,482036.0,23820.0,118842701CC11105047168614112025-08-11,SI,458216,229108,241018,2.0,482036.0,23820.0
74713,118842701,CLINICA KERALTY IBAGUE,CC,51619267,MARIA,NELLY,GODOY,GODOY,P,2025,...,482036.0,23820.0,118842701CC516192678614112025-08-11,SI,458216,229108,241018,2.0,482036.0,23820.0
74714,118842701,CLINICA KERALTY IBAGUE,CC,28764865,LUZ,ANGELA,SOLER,GIRALDO,P,2025,...,482036.0,23820.0,118842701CC287648658614112025-08-13,SI,458216,229108,241018,2.0,482036.0,23820.0

In [48]:
df_salida_resultado_ibague["porcentaje_upc_costo_2024"].value_counts().sort_index()

porcentaje_upc_costo_2024
0.148106     1
0.148437     1
0.148446     1
0.171586     2
0.185133     1
            ..
45.0         3
46.0         1
47.0         1
59.94436     1
92.414222    1
Name: count, Length: 334, dtype: int64[pyarrow]

In [49]:
df_salida_resultado_ibague[
    ["num factura", "tip doc", "num doc", "Codigo Cups", "fec cargo"]
].loc[df_salida_resultado_ibague["porcentaje_upc_costo_2024"] == 12.0]

      num factura tip doc     num doc Codigo Cups   fec cargo
13963   118840431      CC    14216143      903859  2025-08-17
13964   118840431      CC    14216143      903895  2025-08-17
18259   118840564      CC    39553265      129A02  2025-08-16
19383   118840637      CC    31276184      129A02  2025-08-29
21542   118840710      CC    28529397      129A02  2025-08-26
23948   118840786      CC  1097394556      902210  2025-08-14
31786   118840985      CC     2282412      902045  2025-07-30
31787   118840985      CC     2282412      902049  2025-07-30
32490   118840995      CC    93391329      903859  2025-09-05
32503   118840995      CC    93391329      903864  2025-09-05
41980   118841189      CC     5799946      129A02  2025-09-13
42153   118841192      CC     5809810      129A02  2025-09-12
43718   118841275      CC    38142590      903859  2025-09-10
43721   118841275      CC    38142590      903603  2025-09-10
43722   118841275      CC    38142590      903864  2025-09-10
44328   118841292      CC     2870028      903895  2025-09-04
44336   118841292      CC     2870028      903895  2025-09-04
55098   118841590      CC    38216503      902210  2025-09-15
55254   118841591      CC    38242178      129A02  2025-09-20
55263   118841591      CC    38242178      903859  2025-09-20
66519   118841974      CC    65739993      902210  2025-09-24
66731   118841976      CC    65732836      903895  2025-09-17
66733   118841976      CC    65732836      903856  2025-09-17
67572   118842006      CC    65733877      903859  2025-10-02
67579   118842006      CC    65733877      903859  2025-10-02
69013   118842080      CC    38230593      902045  2025-09-28
69014   118842080      CC    38230593      902045  2025-09-28
71746   118842182      CC    93406375      902210  2025-09-06

In [50]:
1_655_088

1655088

In [51]:
# caracterizas 30mil registros que no cruzaron con upc
df_salida_resultado_ibague_no_upc = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["encontrado_upc"] == "NO"
]

# HOJAS

1.NO ENCONTRADOS EN UPC
2.TD NO ENCONTRADOS UPC (CUPS, FACTURA, F_CARGO)
3.retroactivo ibague > retroactivo calculado
4.retroactivo ibague < retroactivo calculado
5.retroactivo ibague = retroactivo calculado
6.duplicados

In [55]:
subset_duplicados = [
    "num factura",
    "desc sucur",
    "tip doc",
    "num doc",
    "pri nom",
    "seg nom",
    "pri ape",
    "seg ape",
    "tip admision",
    "ano adm",
    "num adm",
    "desc entidad",
    "fec cargo",
    "ano cargo",
    "mes cargo",
    "Codigo Cups",
    "desc insumo servicio",
    "desc concepto",
    "valor unit",
    "cantidad",
    "val total cargo",
    "fecha factura",
    "Fecha Ingreso",
    "Fecha Egreso",
    "CODIGO BH",
    "TARIFA 2025",
    "TARIFA VRS CANTIDAD",
    "VALOR RETROACTIVO",
]

In [58]:
df_duplicados = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague.duplicated(subset=subset_duplicados, keep=False)
]

In [ ]:
# 3.retroactivo ibague > retroactivo calculado
# 4.retroactivo ibague < retroactivo calculado
# 5.retroactivo ibague = retroactivo calculado

df_retroactivo_ibague_gt_calculado = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["VALOR RETROACTIVO"].gt(
        df_salida_resultado_ibague["valor_retroactivo"]
    )
]

df_retroactivo_ibague_lt = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["VALOR RETROACTIVO"].lt(
        df_salida_resultado_ibague["valor_retroactivo"]
    )
]