In [1]:
import pandas as pd
import pyarrow as pa
from pathlib import Path

In [2]:
string_pa = pd.ArrowDtype(pa.string())

In [3]:
upc_columns = {
    "prestador": string_pa,
    "depto_prestador": string_pa,
    "mun_prestador": string_pa,
    "no_id": string_pa,
    "tipo_id": string_pa,
    "no_factura": string_pa,
}

In [4]:
upc_data_path = Path(r"..\outputs\upc_data.csv")
resultados_path = Path(r"..\outputs\resultados.csv")

In [5]:
df_upc = pd.read_csv(upc_data_path, sep="|", dtype=upc_columns, dtype_backend="pyarrow")
df_upc.head()

C:\Users\camil\AppData\Local\Temp\ipykernel_57264\1478907086.py:1: DtypeWarning: Columns (0: no_id_ini) have mixed types. Specify dtype option on import or set low_memory=False.
  df_upc = pd.read_csv(upc_data_path, sep="|", dtype=upc_columns, dtype_backend="pyarrow")

,id,id_agrupado,nmradica,hon,cia,cm,prestador,nom_prestador,depto_prestador,mun_prestador,...,desc_cod_dx,desc_cod_dx_rel,desc_munic_usu,desc_dep_usu,desc_reg_usu,desc_munic_pre,desc_dep_pre,desc_reg_pre,EDAD_EXACTA_AÑOS,llave_upc
0,46998292,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI1106231551INSUMO2025-07-24
1,47001990,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI1106231551INSUMO2025-07-24
2,47028049,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,FRACTURA DE LA EPIFISIS INFERIOR DEL HUMERO,FRACTURA DE LA EPIFISIS INFERIOR DEL HUMERO,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI11062315518732052025-07-24
3,47017912,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI1106231551INSUMO2025-07-24
4,47033892,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,CAUSAS DE MORBILIDAD DESCONOCIDAS Y NO ESPECIF...,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,IBAGUÉ,TOLIMA,6 REG CENTRO ORIENTE,None,118839880TI11062315518907012025-07-24

In [6]:
columns_resultado = {
    "num factura": string_pa,
    "tip doc": string_pa,
    "num doc": string_pa,
    "Codigo Cups": string_pa,
}

In [7]:
df_resultado = pd.read_csv(
    resultados_path, sep="|", dtype=columns_resultado, dtype_backend="pyarrow"
)
df_resultado

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,val total cargo,fecha factura,Fecha Ingreso,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,17311,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,902210,18211,18211.0,900.0,118839897CC11104539369022102025-08-29,SI
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,19527,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,890701,20542,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,4683,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,901107,4927,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,5949,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,907106,6258,6258.0,309.0,118839896RC11106118229071062025-08-30,SI
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,17311,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,902210,18211,18211.0,900.0,118839896RC10839430589022102025-08-30,SI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74737,118842701,CLINICA KERALTY IBAGUE,CC,93358730,GERARDO,<NA>,VELASQUEZ,CALDERON,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC933587308905022025-08-19,SI
74738,118842701,CLINICA KERALTY IBAGUE,CC,41707869,MARIA,ANABOLENA,TORRES,SABOGAL,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC417078698905022025-08-19,SI
74739,118842701,CLINICA KERALTY IBAGUE,CC,8297568,MARIO,IVAN,AGUIRRE,PEREZ,P,2025,...,128400,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC82975688905022025-08-19,SI
74740,118842701,CLINICA KERALTY IBAGUE,CC,41662425,MARIA,USDIOLA,AGUIRRE,GALVEZ,P,2025,...,85556,2025-10-31 00:00:00,2025-08-19 00:00:00,2025-08-19 00:00:00,861402,90005,90005.0,4449.0,118842701CC416624258614022025-08-19,SI
74741,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,313424669.05,<NA>,NO

In [8]:
df_upc.loc[
    df_upc.duplicated(
        subset=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], keep=False
    )
].sort_values(
    by=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], ascending=[True] * 5
)[["no_factura", "tipo_id", "no_id", "cups", "desc_cups", "f_prestacion", "vr_pagado"]]

,no_factura,tipo_id,no_id,cups,desc_cups,f_prestacion,vr_pagado
2,118839880,TI,1106231551,873205,RADIOGRAFIA DE CODO,2025-07-24,23150
24,118839880,TI,1106231551,873205,RADIOGRAFIA DE CODO,2025-07-24,23150
0,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,28655
1,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,5743
3,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,3429
...,...,...,...,...,...,...,...
108208,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,3387
108296,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,11493
108302,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,1694
108173,118842701,CC,93404091,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-15,10696
108238,118842701,CC,93404091,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-15,7840

In [9]:
df_tarifas_2025 = pd.read_excel(
    r"..\inputs\30348_ANEXO_800149384_CLINICA KERALTY IBAGUE (2025).xlsx",
    sheet_name="ANEXO",
    skiprows=18,
)

df_tarifas_2025.head()

,Unnamed: 0,TIPO,COD REPS,INTERDEPENDECIA,CODIGO DE HABILITACION - INTERDEPENDENCIA,COD\n(Res Vigente),DESCRIPCION COD (Res Vigente),COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,...,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $2,100","ANESTESIA UVR $1,587",AYUDANTIA UVR $595,"D SALA Mayor 450 UVR $2,331",MATERIALES,TOTAL,OBSERVACIONES,xxx
0,NaN,EV,1102,NO,NO_APLICA,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,No,...,VALOR,"ISS 2001+65,33%",NaN,NaN,NaN,NaN,NaN,20542.0,NaN,NaN
1,NaN,EV,706,NO,NO_APLICA,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,No,...,VALOR,"ISS 2001+65,33%",NaN,NaN,NaN,NaN,NaN,18211.0,NaN,NaN
2,NaN,EV,129,NO,NO_APLICA,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,No,...,VALOR,"ISS 2001+65,33%",NaN,NaN,NaN,NaN,NaN,24957.0,NaN,NaN
3,NaN,EV,706,NO,NO_APLICA,903895,CREATININA EN SUERO U OTROS FLUIDOS,903895,CREATININA EN SUERO U OTROS FLUIDOS,No,...,PROPIA,PROPIA,NaN,NaN,NaN,NaN,NaN,4773.0,NaN,NaN
4,NaN,EV,706,NO,NO_APLICA,903883,GLUCOSA SEMIAUTOMATIZADA [GLUCOMETRÍA],903883,GLUCOSA SEMIAUTOMATIZADA [GLUCOMETRIA],No,...,PROPIA,PROPIA,NaN,NaN,NaN,NaN,NaN,4322.0,NaN,NaN

In [10]:
df_merge_upc = df_upc.merge(
    df_tarifas_2025.dropna(subset=["COD EPS"]),
    how="left",
    left_on="cups",
    right_on="COD EPS",
    suffixes=("_upc", "_tarifa2025"),
)

df_merge_upc.head()

,id,id_agrupado,nmradica,hon,cia,cm,prestador,nom_prestador,depto_prestador,mun_prestador,...,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $2,100","ANESTESIA UVR $1,587",AYUDANTIA UVR $595,"D SALA Mayor 450 UVR $2,331",MATERIALES,TOTAL,OBSERVACIONES,xxx
0,46998292,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47001990,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,47028049,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,VALOR,"ISS 2001+65,33%",NaN,NaN,NaN,NaN,NaN,24353.0,NaN,NaN
3,47017912,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,47033892,None,1790611239,SERVICIO URGENCIA,None,None,800149384,CLINICA KERALTY IBAGUE,73,73001,...,VALOR,"ISS 2001+65,33%",NaN,NaN,NaN,NaN,NaN,20542.0,NaN,NaN

In [11]:
df_merge_upc.loc[
    df_merge_upc.duplicated(
        subset=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], keep=False
    )
].sort_values(
    by=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], ascending=[True] * 5
)[
    [
        "no_factura",
        "tipo_id",
        "no_id",
        "cups",
        "desc_cups",
        "f_prestacion",
        "vr_pagado",
    ]
]

,no_factura,tipo_id,no_id,cups,desc_cups,f_prestacion,vr_pagado
2,118839880,TI,1106231551,873205,RADIOGRAFIA DE CODO,2025-07-24,23150
24,118839880,TI,1106231551,873205,RADIOGRAFIA DE CODO,2025-07-24,23150
0,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,28655
1,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,5743
3,118839880,TI,1106231551,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-07-24,3429
...,...,...,...,...,...,...,...
108208,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,3387
108296,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,11493
108302,118842701,CC,93382641,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-08,1694
108173,118842701,CC,93404091,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-15,10696
108238,118842701,CC,93404091,INSUMO,INSUMOS Y MEDICAMENTOS INTRAHOSPITALARIOS,2025-08-15,7840

In [12]:
agrupacion_costo_upc = df_upc.groupby(
    ["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], as_index=False
).agg({"vr_pagado": "sum"})

agrupacion_costo_upc

      no_factura tipo_id       no_id    cups f_prestacion  vr_pagado
0      118839880      TI  1106231551  361916   2025-07-24      37464
1      118839880      TI  1106231551  5DS004   2025-07-24      52540
2      118839880      TI  1106231551  793204   2025-07-24     199600
3      118839880      TI  1106231551  873121   2025-07-24      30002
4      118839880      TI  1106231551  873205   2025-07-24      46300
...          ...     ...         ...     ...          ...        ...
60447    1419129      TI  1110499859  890236   2025-09-12      43808
60448    1419129      TI  1139224382  890336   2025-09-29      43242
60449    1419129      TI  1141721700  890236   2025-09-22      43808
60450    1419129      TI  1197468881  890294   2025-09-23      51798
60451    1419129      TI  1233505893  890336   2025-09-01      43242

[60452 rows x 6 columns]

In [13]:
df_resultado_merge_upc = df_resultado.merge(
    agrupacion_costo_upc,
    how="left",
    left_on=["num factura", "tip doc", "num doc", "Codigo Cups", "fec cargo"],
    right_on=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"],
    suffixes=("_resultado", "_upc"),
)

df_resultado_merge_upc.drop(
    columns=["no_factura", "tipo_id", "no_id", "cups", "f_prestacion"], inplace=True
)

df_resultado_merge_upc.head()

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,fecha factura,Fecha Ingreso,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc,vr_pagado
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,902210,18211,18211.0,900.0,118839897CC11104539369022102025-08-29,SI,17311
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-09-01 00:00:00,2025-08-29 00:00:00,2025-08-31 00:00:00,890701,20542,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI,19527
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,901107,4927,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO,<NA>
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-31 00:00:00,907106,6258,6258.0,309.0,118839896RC11106118229071062025-08-30,SI,5949
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,2025-09-01 00:00:00,2025-08-30 00:00:00,2025-08-30 00:00:00,902210,18211,18211.0,900.0,118839896RC10839430589022102025-08-30,SI,17311

In [14]:
df_tarifas_2024_27000 = pd.read_excel(
    r"..\inputs\27000_ANEXO_800149384_CLINICA KERALTY IBAGUE_(2024).xlsx",
    sheet_name="ANEXO",
    skiprows=17,
    dtype_backend="pyarrow",
)

df_tarifas_2024_27000.head()

,Unnamed: 0,TIPO,COD REPS,COD\n(Res Vigente 2336 de 2023),COD IPS,DESCRIPCION IPS,COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),...,FORMA DE LIQUIDAR,TARIFA DEFINIDA,"HONORARIO UVR $1,996","ANESTESIA UVR $1,509",AYUDANTIA UVR $566,"D SALA Mayor 450 UVR $2,216",MATERIALES,TOTAL,OBSERVACIONES,Unnamed: 20
0,None,EV,1102,890701,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,No,890701,...,VALOR,"ISS 2001+57,16%",<NA>,<NA>,<NA>,<NA>,<NA>,19527,<NA>,None
1,None,EV,706,902210,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,No,902210,...,VALOR,"ISS 2001+57,16%",<NA>,<NA>,<NA>,<NA>,<NA>,17311,<NA>,None
2,None,EV,129,890602,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,No,890602,...,VALOR,"ISS 2001+57,16%",<NA>,<NA>,<NA>,<NA>,<NA>,23723,<NA>,None
3,None,EV,706,903895,903895,CREATININA EN SUERO U OTROS FLUIDOS,903895,CREATININA EN SUERO U OTROS FLUIDOS,No,<NA>,...,PROPIA,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,4537,<NA>,None
4,None,EV,706,903856,903856,NITROGENO UREICO,903856,NITROGENO UREICO,No,903856,...,VALOR,"ISS 2001+57,16%",<NA>,<NA>,<NA>,<NA>,<NA>,5760,<NA>,None

In [15]:
df_tarifas_2024_27467 = pd.read_excel(
    r"..\inputs\27467_ANEXO_800149384_CLINICA KERALTY IBAGUE_(2024).xlsx",
    sheet_name="ANEXO",
    skiprows=17,
    dtype_backend="pyarrow",
)

df_tarifas_2024_27467.head()

,Unnamed: 0,TIPO,COD REPS,COD\n(Res Vigente 2336 de 2023),COD IPS,DESCRIPCION IPS,COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),UVR/VALOR,TARIFA DEFINIDA,HONORARIO,ANESTESIA,AYUDANTIA,D SALA,MATERIALES,TOTAL,OBSERVACIONES,AMBITO
0,None,EV,129,890474,890474,INTERCONSULTA POR ESPECIALISTA EN NEUROLOGÍA,890474,INTERCONSULTA POR NEUROLOGIA,No,<NA>,<NA>,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,84637,<NA>,H-U
1,None,EV,129,890433,890433,INTERCONSULTA POR ESPECIALISTA EN CIRUGÍA DE T...,890433,INTERCONSULTA POR CIRUGIA DE TORAX,No,<NA>,<NA>,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,64200,<NA>,H-U
2,None,PQ,215,601101,601101PQ,BIOPSIA CERRADA DE PROSTATA POR ABORDAJE TRANS...,601101PQ,BIOPSIA CERRADA DE PROSTATA POR ABORDAJE TRANS...,No,<NA>,<NA>,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,1526960,Se solicita Replica de Paquete,A-H
3,None,EV,234,324102,324102,LOBECTOMÍA SEGMENTARIA POR TORACOSCOPIA,324102,LOBECTOMIA SEGMENTARIA POR TORACOSCOPIA,Si,323100,150,"PROPIA HON Demas Componentes ISS 2001+57,16%",2700000,226350,84900,292962,220213,3524425,<NA>,H
4,None,PQ,215,601103,601103PQ,BIOPSIA CERRADA DE PROSTATA POR SATURACION ABO...,601103PQ,BIOPSIA CERRADA DE PROSTATA POR SATURACION ABO...,No,<NA>,<NA>,PROPIA,<NA>,<NA>,<NA>,<NA>,<NA>,1046460,Se solicita Replica de Paquete,A-H

In [16]:
df_tarifas_2024_27467.dropna(subset=["COD EPS"], inplace=True)
df_tarifas_2024_27000.dropna(subset=["COD EPS"], inplace=True)

In [17]:
df_tarifas_2024 = pd.concat(
    [df_tarifas_2024_27000, df_tarifas_2024_27467], ignore_index=True
)

df_tarifas_2024.head()

,Unnamed: 0,TIPO,COD REPS,COD\n(Res Vigente 2336 de 2023),COD IPS,DESCRIPCION IPS,COD EPS,DESCRIPCION CUPS,HABILITA CONCEPTOS,COD HOMOLOGO Manual tarifario\n(ISS o SOAT),...,"D SALA Mayor 450 UVR $2,216",MATERIALES,TOTAL,OBSERVACIONES,Unnamed: 20,HONORARIO,ANESTESIA,AYUDANTIA,D SALA,AMBITO
0,None,EV,1102,890701,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,890701,CONSULTA DE URGENCIAS POR MEDICINA GENERAL,No,890701,...,<NA>,<NA>,19527,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>
1,None,EV,706,902210,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,902210,HEMOGRAMA IV (HEMOGLOBINA HEMATOCRITO RECUENTO...,No,902210,...,<NA>,<NA>,17311,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>
2,None,EV,129,890602,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,890602,CUIDADO (MANEJO) INTRAHOSPITALARIO POR MEDICIN...,No,890602,...,<NA>,<NA>,23723,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>
3,None,EV,706,903895,903895,CREATININA EN SUERO U OTROS FLUIDOS,903895,CREATININA EN SUERO U OTROS FLUIDOS,No,<NA>,...,<NA>,<NA>,4537,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>
4,None,EV,706,903856,903856,NITROGENO UREICO,903856,NITROGENO UREICO,No,903856,...,<NA>,<NA>,5760,<NA>,None,<NA>,<NA>,<NA>,<NA>,<NA>

In [18]:
df_resultado_merge_tarifas_2024 = df_resultado_merge_upc.merge(
    df_tarifas_2024,
    how="left",
    left_on="Codigo Cups",
    right_on="COD EPS",
    suffixes=("_upc", "_tarifa2024"),
)

In [19]:
df_resultado_merge_tarifas_2025 = df_resultado_merge_tarifas_2024.merge(
    df_tarifas_2025.dropna(subset=["COD EPS"]),
    how="left",
    left_on="Codigo Cups",
    right_on="COD EPS",
    suffixes=("_tarifa2024", "_tarifa2025"),
)

In [20]:
cols_salida = [
    "num factura",
    "desc sucur",
    "tip doc",
    "num doc",
    "pri nom",
    "seg nom",
    "pri ape",
    "seg ape",
    "tip admision",
    "ano adm",
    "num adm",
    "desc entidad",
    "fec cargo",
    "ano cargo",
    "mes cargo",
    "Codigo Cups",
    "desc insumo servicio",
    "desc concepto",
    "valor unit",
    "cantidad",
    "val total cargo",
    "fecha factura",
    "Fecha Ingreso",
    "Fecha Egreso",
    "CODIGO BH",
    "TARIFA 2025",
    "TARIFA VRS CANTIDAD",
    "VALOR RETROACTIVO",
    "llave_retroactivo",
    "encontrado_upc",
    "vr_pagado",
    "TOTAL_tarifa2024",
    "TOTAL_tarifa2025",
]

In [21]:
df_salida_resultado_ibague = df_resultado_merge_tarifas_2025[cols_salida].copy()

In [22]:
df_salida_resultado_ibague

,num factura,desc sucur,tip doc,num doc,pri nom,seg nom,pri ape,seg ape,tip admision,ano adm,...,Fecha Egreso,CODIGO BH,TARIFA 2025,TARIFA VRS CANTIDAD,VALOR RETROACTIVO,llave_retroactivo,encontrado_upc,vr_pagado,TOTAL_tarifa2024,TOTAL_tarifa2025
0,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-08-31 00:00:00,902210,18211,18211.0,900.0,118839897CC11104539369022102025-08-29,SI,17311,17311,18211.0
1,118839897,CLINICA KERALTY IBAGUE,CC,1110453936,XIOMARA,ESPERANZA,ARCINIEGAS,ARANDA,U,2025,...,2025-08-31 00:00:00,890701,20542,20542.0,1015.0,118839897CC11104539368907012025-08-29,SI,19527,19527,20542.0
2,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-08-31 00:00:00,901107,4927,4927.0,244.0,118839896RC1110611822OMG83292025-08-30,NO,<NA>,<NA>,NaN
3,118839896,CLINICA KERALTY IBAGUE,RC,1110611822,ADRIAN,KARIM,CAYCEDO,MEDINA,U,2025,...,2025-08-31 00:00:00,907106,6258,6258.0,309.0,118839896RC11106118229071062025-08-30,SI,5949,5949,6258.0
4,118839896,CLINICA KERALTY IBAGUE,RC,1083943058,ALAIA,VICTORIA,SANCHEZ,URRIAGO,U,2025,...,2025-08-30 00:00:00,902210,18211,18211.0,900.0,118839896RC10839430589022102025-08-30,SI,17311,17311,18211.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74737,118842701,CLINICA KERALTY IBAGUE,CC,93358730,GERARDO,<NA>,VELASQUEZ,CALDERON,P,2025,...,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC933587308905022025-08-19,SI,128400,128400,135077.0
74738,118842701,CLINICA KERALTY IBAGUE,CC,41707869,MARIA,ANABOLENA,TORRES,SABOGAL,P,2025,...,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC417078698905022025-08-19,SI,128400,128400,135077.0
74739,118842701,CLINICA KERALTY IBAGUE,CC,8297568,MARIO,IVAN,AGUIRRE,PEREZ,P,2025,...,2025-08-19 00:00:00,890502,135077,135077.0,6677.0,118842701CC82975688905022025-08-19,SI,128400,128400,135077.0
74740,118842701,CLINICA KERALTY IBAGUE,CC,41662425,MARIA,USDIOLA,AGUIRRE,GALVEZ,P,2025,...,2025-08-19 00:00:00,861402,90005,90005.0,4449.0,118842701CC416624258614022025-08-19,SI,85556,85556,90005.0
74741,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,313424669.05,<NA>,NO,<NA>,<NA>,NaN

## Operaciones

In [23]:
# vr_pagado upc / total_2024 = porcentaje_upc_costo_2024
# porcentaje_upc_costo_2024 * total_2025 = vr_pagado 2025
# vr_pagado 2025 - vr_pagado upc = retroactivo

In [24]:
df_salida_resultado_ibague = df_salida_resultado_ibague.assign(
    porcentaje_upc_costo_2024=lambda df_: df_["vr_pagado"] / df_["TOTAL_tarifa2024"],
    vr_pagado_2025=lambda df_: df_["porcentaje_upc_costo_2024"]
    * df_["TOTAL_tarifa2025"],
    valor_retroactivo=lambda df_: df_["vr_pagado_2025"] - df_["vr_pagado"],
)

In [33]:
# caracterizas 30mil registros que no cruzaron con upc
df_salida_resultado_ibague_no_upc = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["encontrado_upc"] == "NO"
]

In [35]:
# caracterizas 30mil registros que no cruzaron con upc
df_salida_resultado_ibague_si_upc = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["encontrado_upc"] == "SI"
]

# HOJAS

1.NO ENCONTRADOS EN UPC
2.TD NO ENCONTRADOS UPC (CUPS, FACTURA, F_CARGO)
3.retroactivo ibague > retroactivo calculado
4.retroactivo ibague < retroactivo calculado
5.retroactivo ibague = retroactivo calculado
6.duplicados

In [26]:
subset_duplicados = [
    "num factura",
    "desc sucur",
    "tip doc",
    "num doc",
    "pri nom",
    "seg nom",
    "pri ape",
    "seg ape",
    "tip admision",
    "ano adm",
    "num adm",
    "desc entidad",
    "fec cargo",
    "ano cargo",
    "mes cargo",
    "Codigo Cups",
    "desc insumo servicio",
    "desc concepto",
    "valor unit",
    "cantidad",
    "val total cargo",
    "fecha factura",
    "Fecha Ingreso",
    "Fecha Egreso",
    "CODIGO BH",
    "TARIFA 2025",
    "TARIFA VRS CANTIDAD",
    "VALOR RETROACTIVO",
]

In [27]:
df_duplicados = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague.duplicated(subset=subset_duplicados, keep=False)
]

In [28]:
df_salida_resultado_ibague["DUPLICADO"] = df_salida_resultado_ibague.duplicated(
    subset=subset_duplicados, keep=False
)

df_salida_resultado_ibague = df_salida_resultado_ibague.assign(
    DUPLICADO=lambda df_: df_["DUPLICADO"].map({True: "DUPLICADO", False: "UNICO"}),
    diferencia_retroactivo=lambda df_: df_["VALOR RETROACTIVO"]
    - df_["valor_retroactivo"],
).dropna(subset=["Codigo Cups"])

In [29]:
# 3.retroactivo ibague > retroactivo calculado
# 4.retroactivo ibague < retroactivo calculado
# 5.retroactivo ibague = retroactivo calculado

df_retroactivo_ibague_gt_calculado = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["VALOR RETROACTIVO"].gt(
        df_salida_resultado_ibague["valor_retroactivo"]
    )
]

df_retroactivo_ibague_lt = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["VALOR RETROACTIVO"].lt(
        df_salida_resultado_ibague["valor_retroactivo"]
    )
]

df_retroactivo_ibague_eq = df_salida_resultado_ibague.loc[
    df_salida_resultado_ibague["VALOR RETROACTIVO"].eq(
        df_salida_resultado_ibague["valor_retroactivo"]
    )
]

In [30]:
with pd.ExcelWriter(
    r"..\outputs\analisis_retroactivo_ibague.xlsx",
    engine="openpyxl",
) as writer:
    df_salida_resultado_ibague.to_excel(
        writer, sheet_name="resultado_completo", index=False
    )

    df_duplicados.to_excel(writer, sheet_name="duplicados", index=False)

    df_retroactivo_ibague_gt_calculado.to_excel(
        writer, sheet_name="retroactivo_gt_calculado", index=False
    )
    df_retroactivo_ibague_lt.to_excel(
        writer, sheet_name="retroactivo_lt_calculado", index=False
    )
    df_retroactivo_ibague_eq.to_excel(
        writer, sheet_name="retroactivo_eq_calculado", index=False
    )

# Analisis

In [ ]:
df_salida_resultado_ibague["encontrado_upc"].value_counts(normalize=True)

encontrado_upc
SI    0.562449
NO    0.437551
Name: proportion, dtype: double[pyarrow]